### ISSUE TITLE
Will you use HTMX?

### ISSUE THREAD

**Issue by Mazgagzam** [tshipenchko/WT1207#1]
Will you use HTMX?
HTMX is a library that allows you to access modern browser features directly from HTML, rather than using javascript

**Comment by merura** [comment]
I don't really think that I will use HTMX. 
It's repository for web technologies course at university, so I have to follow course's syllabus after all :c

But anyway, HTMX sounds interesting. Maybe in the future I'll use it just for fun.

**Comment by tshipenchko** [comment]
I don't really think that I will use HTMX. 
It's repository for web technologies (Frontend using HTML & CSS & JS), so I have to follow course's syllabus after all :c

But anyway, HTMX sounds interesting. Maybe in the future I'll use it just for fun.

**Comment by Mazgagzam** [comment]
HTMX is mixing javascript and react. Add attributes and you can write a little code in a js HTMX will do the rest.

**Comment by Mazgagzam** [comment]
Is there any way to remove this Issues?

**Comment by merura** [comment]
I think there is no way to remove an issue. Don't mind anyway, I'm going to use HTMX one day in one of assignments, if it's possible.

**Comment by Mazgagzam** [comment]
I'm very stupid so here it is https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue

**Comment by merura** [comment]
https://htmx.org/essays/#memes

**Comment by merura** [comment]
okay. i didn't used it
we just didn't use a backend :c, so there is place for `HTMX` technology
