### ISSUE TITLE
Final exam

### ISSUE THREAD

**Issue by merura** [tshipenchko/WT1207#4]
In this final project, everyone must create a new website individually! Read the requirement very attentively, as your grade will totally depend on it.

The whole web project must consist of at least 4 web pages (on different pages through NavBar), all using HTML, CSS, Bootstrap and JavaScript. 

Don’t forget, your project must contain favicon, font awesome icons, it must be responsive for all screen types and should be published in GitHub Pages. You will not receive additional points for this, but if these requirements are not met, the instructor has the right to reduce your grade. Adding footer is necessary (fill out with your information)

Requirements | Grading
-- | --
Do 			research about your topic. Before starting a website, try to do 			some research. Use https://w3schools.com/ 			for your help. | 5%
Draw 			a 			wireframe 			and add it as a document (pdf) into the project’s folder. Figma 			is good idea. | 5%
Design 			and Structure. Go 			to the official documentation of Bootstrap (section Components): 			https://getbootstrap.com/ 			docs/4.6/components/ explore new  			 			 			components 			not covered in the lectures  			 			and 			use at least two new components in your project (carousel, cards 			and etc.). | 25%
Use 			your own 			creativity. 			Don’t make it boring 			or overwhelming 			with information. If your website is organized, shows facts rather 			than having much information, that is quite good. It should also 			be logical and structured. | 15%
Use 			JavaScript 			 			Explore 			new components of JS elements. Your website must be interactive. 			 			Add 			animations, pop-up menus, clickable buttons, control multimedia, 			sound with JS functions. 			 			Keep 			animations brief with no flashing. Flashing 			is annoying. | 30%
Usage 			of JQuery 			 			Use 			JQuery for CSS manipulation. 			Create 			animation with JQuery.(differ from the JS part animation ) | 10%
Publish 			in Github 			Pages. 			Provide the link of your website. | 10%
Total | 100%

Design and Structure
Use:
- Bootstrap Buttons
- Navigation bar
- Containers
- Grid layout system

---
Checklist!
- [x] Do research (I did a lot for creating the game)
- [x] Draw a wireframe 
- [x] Design and Structure (Yeah, black color is cool)
- [x] Use cool components, ex: carousel, cards and etc.
- [x] Use your own creativity (Most creative site ever!) 
- [x] Use JavaScript, ex: animations, pop-up menus, clickable buttons, control multimedia, sound with JS functions
- [x] Use JQuery (I did it at least in the game)
- [x] Publish in Github Pages (Pff easy!)
- [x] at least 4 pages

**Comment by tshipenchko** [comment]
Design and Structure
Use:
- Bootstrap Buttons 
- Navigation bar 
- Containers  
- Grid layout system

**Comment by Mazgagzam** [comment]
And is this what you should do?

**Comment by merura** [comment]
@Mazgagzam yes, it's the requirement

**Comment by Mazgagzam** [comment]
I found out that you are on vacation next week, I look forward to them more than my holidays

**Comment by merura** [comment]
Yes, I see. It's so sad really!
I will definitely take the time to return to telegram during the holidays
